I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1114, in script call
    call day36 from _call_day36
  File "game/choices/choices.rpy", line 360, in script
    $increaseStress(14.2)
ScriptError: could not find label 'gameover'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 617, in main
    run(restart)
  File "renpy/main.py", line 148, in run
    renpy.execution.run_context(True)
  File "renpy/execution.py", line 922, in run_context
    context.run()
  File "game/script.rpy", line 1114, in script call
    call day36 from _call_day36
  File "game/choices/choices.rpy", line 360, in script
    $increaseStress(14.2)
  File "renpy/script.py", line 910, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'gameover'.

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
STRELL 2.0
Tue Jun 22 19:35:50 2021
